## You have a matrix MxN that represents a map. There are 2 possible states on the map: 1 - islands, 0 - ocean. Your task is to calculate the number of islands in the most effective way. Please write code in Python 3.


In [30]:
while True:
    try:
        num_rows = int(input("Enter number of ROWS: "))
    except ValueError:
        print("Please enter a valid integer num_rows >= 1")
        continue
    if num_rows >= 1:
        #print(f'You entered: {num_rows}')
        break
    else:
        print('Number of ROWS must be equal or bigger than 1')
        
while True:
    try:
        num_cols = int(input("Enter number of COLUMNS: "))
    except ValueError:
        print("Please enter a valid integer n >= 1")
        continue
    if num_cols >= 1:
        #print(f'You entered: {num_cols}')
        break
    else:
        print('Number of COLUMNS must be equal or bigger than 1')

Enter number of ROWS: 3
Enter number of COLUMNS: 4


In [31]:
import numpy as np

matrix = np.random.randint(2, size=(num_rows, num_cols))

print(matrix)

[[1 0 0 1]
 [1 1 1 0]
 [1 1 0 0]]


In [32]:

np.sum(matrix)

7